include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_annotating_with_dynamic: true
    prefer_single_quotes: true
    require_trailing_commas: true
    avoid_print: true
    prefer_is_empty: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_redundant_argument_values: true
    flutter_style_todos: true
    prefer_if_null_operators: true
