name: ds_kit
description: 'A new Flutter package project.'
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: AfacadFlux
      fonts:
        - asset: assets/fonts/afacad.ttf

    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower.ttf

  uses-material-design: true
