name: Check Code Quality

on:
  push:
    branches:
      - main
      - dev
      - sit
  pull_request:
    branches:
      - main
      - dev
      - sit

jobs:
  build:
    name: Qualities Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3' 
        cache: true
        
    - name: Install Melos
      run: dart pub global activate melos

    - name: Bootstrap Melos
      run: melos bootstrap

    - name: Verify Formatting
      run: melos run format

    - name: Analyze Project Source
      run: melos run analyze  
          

